### ISSUE TITLE
pb: maj Dépôt alternatif

### ISSUE THREAD

**Issue by nanart59** [franck-paul/dmHelper#2]
Bonjour
Je viens d'installer dmHelper et Hosting Monitor Dashboard
Mise à jour Hosting Monitor Dashboard ok
Message : Requires dmHelper version 2.0, but version 1.0.1 is installed
je tente de mettre à jour dmHelper.
Message : **Fichier zip de module vide**

En installant manuellement le fichier obtenu ici: OK

Pb de lien ???

**Comment by franck-paul** [comment]
Oui, le lien est incorrect, je vais corriger :-)
